#!/usr/bin/env bash

MODULE_NAME=doorlock
GLOBAL_NAME=Doorlock

rm -rf dist/*
esbuild src/index.ts --bundle --target=chrome60,firefox60,safari12,edge18 \
  --outfile=dist/$MODULE_NAME.js --sourcemap --format=iife --global-name=$GLOBAL_NAME \
  && esbuild src/index.ts --bundle --target=chrome60,firefox60,safari12,edge18 \
  --outfile=dist/$MODULE_NAME.min.js --minify --format=iife --global-name=$GLOBAL_NAME \
  && tsc -d --emitDeclarationOnly --rootDir src --outDir dist \
  && mv dist/index.d.ts dist/$MODULE_NAME.d.ts \
  && rm -rf dist/interfaces.d.ts \
  && refup dist/$MODULE_NAME.js $GLOBAL_NAME \
  && refup dist/$MODULE_NAME.min.js $GLOBAL_NAME \
  || exit 1
